### ISSUE TITLE
Added some ssh options, but not perfect

### ISSUE THREAD

**Issue by ghost** [Doka-NT/ssh-manager#1]
Hi, as we were in contact via email some minutes ago, I am creating this issue with added changed files.
Added features:
- added config option for ssh arguments (like "-Y" or "-C" or "-YC")
- added config option for user/login name (used with "-l" for ssh)
- changed handling of port option
- added config option to define command as last argument on ssh command line

As I am not experienced in Python my changes do not work with "multi-arguments" (for example  "-Y -C") and do not know how to fix/handle it (would be great if you know how)

[changed_files.zip](https://github.com/Doka-NT/ssh-manager/files/469909/changed_files.zip)

**Comment by Doka-NT** [comment]
Hello! Thank you for your feedback!
Please tell, you need to add specific arguments to specific connection or to all available connections?

**Comment by ghost** [comment]
Hello and you are welcome :-)

The desired behavior is to be able to define one or more arguments for each configured connection in json config file, for example ...
- with "-Y"
- with "-C"
- with "-C -L 22022:localhost:22"
- with "-L 23022:localhost:22 -L 8291:localhost:8291"
  ... and so on.

Unfortunately with my change, when I put the following into the json config to a connection "args" = "-C -Y"  the ssh does not work, as it considers it as one big argument (and does not know it) and not two separated arguments (as I wished)

**Comment by Doka-NT** [comment]
Now you can pass arguments in specific connections

``` json
    {
      "host": "localhost",
      "label": "Localhost with default port",
      "args": [
        "-l", "my_username"
      ]
    }
```

**Comment by ghost** [comment]
Cool, thanks :+1:
